version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"

  spring-boot-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-manager
    ports:
      - "8080:8080"
    depends_on:
      - mongodb