aws:
  s3:
    bucketName: {BUCKET_NAME:videos-manager-to-process}
    accessKey: {AWS_ACCESS_KEY:aaaaaaaaaaa}
    secretKey: {AWS_SECRET_KEY:1111111111}
  sqs:
    queue:
      url: https://sqs.us-east-1.amazonaws.com/326232041794/test-console
  region: us-east-1


  spring:
    application:
      name: video-manager
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
    datasource:
      url: jdbc:h2:mem:videos
      driverClassName: org.h2.Driver
      username: admin
      password: admin
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
    h2:
      console:
        enabled: true
        path: /h2-console