name: Build and Deploy to Amazon ECR

on:
  push:
    branches:
      - main
      - mem-database
      - teste

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: aws-lab-fiap

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Compile
        run: mvn clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Authenticate on AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: 'us-east-1'

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository (if not exists)
        run: |
          aws ecr describe-repositories --repository-names video-manager-application || \
          aws ecr create-repository --repository-name video-manager-application

      - name: Build and push Docker image using Docker Compose
        env:
          ECR_REPOSITORY: video-manager-application
          IMAGE_TAG: ${{ github.sha }}
          AWS_ACCOUNT_ID: 990374739777
        run: |
          # Build the Docker Compose images (only spring-boot-app image will be built)
          docker compose -f docker-compose.yml build spring-boot-app

          # Tag the image with the ECR repository
          docker tag video-manager:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

          # Push the image to ECR
          docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
